### ISSUE TITLE
Add topic tags to repository

### ISSUE THREAD

**Issue by ghost** [TUD-STKS/VocalTractLab-dev#19]
In my case, I only found this project by chance mentioned in a blog post about articulatory synthesis.
Adding topic tags would make the project much more discoverable to Github users (on the Code tab of this repo, edit the About section on the left). For example: "speech-synthesis", "vocoder", "speech-analysis", "articulatory-synthesis".

**Comment by Simon-Stone** [comment]
Great suggestion, thank you very much! I added the suggested tags.
