### ISSUE TITLE
The representation of geometric glottis parameter "Phase lag" is inconsistent

### ISSUE THREAD

**Issue by paul-krug** [TUD-STKS/VocalTractLab-dev#9]
Phase lag is a parameter measured in radians but is shown as an angle in degrees in the glottis model window. This is inconsistent with the supra glottal parameter JA, which is measured and displayed in degrees.

**Comment by Simon-Stone** [comment]
This is by design. The field `userFactor` in the struct `Parameter` can be used to convert between displayed ("user") units and CGS units (used in the actual calculations).
